{% set name = "nzpy" %}
{% set version = "1.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98cc17b2c6cf24c816ef69205a3d85d2e740eedd1e7787641e87dc4a28aca9a3

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - scramp =1.1.0

test:
  imports:
    - nzpy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ibm/nzpy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A pure python driver for IBM Netezza'
  description: |
    nzpy is a pure-Python IBM Netezza driver that complies with DB-API 2.0.
    It is tested on Python versions 3.5+. It is supported with NPS 11.1.2.x
    and later. Although nzpy works with older NPS versions but it do not
    support few features such as external table, parameter style query etc.
  doc_url: https://github.com/IBM/nzpy/blob/master/README.md
  dev_url: https://github.com/ibm/nzpy

extra:
  recipe-maintainers:
    - mcg1969
